[[cells]]
name = "ckb_auth"
enable_type_id = false
location = { file = "build/release/ckb_auth" }
[[cells]]
name = "unisat_lock"
enable_type_id = true
location = { file = "build/release/unisat_lock" }

# Dep group cells
[[dep_groups]]
name = "ckb_auth_locks"
cells = ["ckb_auth", "unisat_lock"]

# The lock script set to output cells
[lock]
code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
args = "0xc8328aabcd9b9e8e64fbc566c4385c3bdeb219d7"
hash_type = "type"
